{{- include "ffc-helm-library.container-secret" (list . "ffc-grants-file-creation.container-secret") -}}
{{- define "ffc-grants-file-creation.container-secret" -}}
stringData:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.appInsights.key | quote }}
{{- end -}}