version: '3.8'

services:
  ffc-grants-file-creation:
    build:
      context: .
      target: production
    image: ffc-grants-file-creation
    container_name: ffc-grants-file-creation
    environment: 
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST:-notset}
      SERVICE_BUS_PASSWORD: ${SERVICE_BUS_PASSWORD:-notset}
      SERVICE_BUS_USER: ${SERVICE_BUS_USER:-notset}
