version: '3.8'

services:
  ffc-grants-file-creation:
    build:
      context: .
      target: production
    image: ffc-grants-file-creation
    container_name: ffc-grants-file-creation
    environment: {}
