version: '3.8'

services:
  ffc-grants-file-creation:
    build:
      context: .
      target: production
    image: ffc-grants-file-creation
    container_name: ffc-grants-file-creation
    environment:
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST:-notset}
      SERVICE_BUS_PASSWORD: ${SERVICE_BUS_PASSWORD:-notset}
      SERVICE_BUS_USER: ${SERVICE_BUS_USER:-notset}
      FILE_CREATED_TOPIC_ADDRESS: ${FILE_CREATED_TOPIC_ADDRESS:-notset}
      DESIRABILITY_SUBMITTED_SUBSCRIPTION_ADDRESS: ${DESIRABILITY_SUBMITTED_SUBSCRIPTION_ADDRESS:-notset}
      DESIRABILITY_SUBMITTED_TOPIC_ADDRESS: ${DESIRABILITY_SUBMITTED_TOPIC_ADDRESS:-notset}
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY:-notset}
